### PR TITLE
Add iCubGazeboV2_5 model

### PR DESCRIPTION
**Pull request by diegoferigo**
The iCub model has been taken from [iCubGazeboV2_5/model.urdf](https://github.com/robotology/icub-models/blob/b1aa55bbe2/iCub/robots/iCubGazeboV2_5/model.urdf) and adapted to work in Ignition Gazebo.

iCubGazeboV2_5

### CODE REVIEW

**Comment by diegoferigo** [comment]
It speeds up development though :) I didn't consider comparisons, you're right. It's too late now to roll back, a rebase would not work in this case.

**Comment by traversaro** [comment]
> It speeds up development though :)

Just to understand, why four spaces indent speeds up the development over two spaces indent? Note that those files were already indented programmatically using the `pretty_print` option of lxml.

**Comment by diegoferigo** [comment]
It's not the indentation that speeds up the development. Simply, when I save in my setup all files get reformatted, and it happened that I had the 4 spaces enabled by default.

**Comment by diegoferigo** [comment]
As a workaround, I can format back the file to 2 spaces. One extra commit would not harm :)

**Comment by traversaro** [comment]
> 
> 
> As a workaround, I can format back the file to 2 spaces. One extra commit would not harm :)

As you prefer, you can even just re-format back when we will need comparisons.

**Pull request merged**
